{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "policy-models-simulator.serviceAccountName" . }}
  labels:
{{ include "policy-models-simulator.labels" . | indent 4 }}
{{- end -}}
